version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "shonin/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "shonin/build.gradle" }}
#      - run:
#          name: Run Tests
#          command: ./gradlew lint test
      - store_artifacts:
          path: shonin/build/reports
          destination: reports
      - store_test_results:
          path: shonin/build/test-results
      - run:
          name: Run Build
          command: ./gradlew build
      - store_artifacts:
          path: shonin/build/outputs/apk/debug/
          destination: artifact-file
      - run:
          name: Upload to Slack
          command: |
            export GIT_COMMIT_DESC=$(git log --format=oneline -n 1 | sed -E 's/^[^ ]+ (.*)$/\1/g')
            curl -F file=@shonin/build/outputs/apk/debug/app-debug.apk -F channels=$SLACK_CHANNEL -F token=$SLACK_API_TOKEN -F title="${CIRCLE_PROJECT_REPONAME} | branch -> ${CIRCLE_BRANCH} | commit -> ${GIT_COMMIT_DESC}"  https://slack.com/api/files.upload